#!/bin/sh
. /lib/functions.sh

[ -f /etc/config/dns_rewrite ] || {
	touch /etc/config/dns_rewrite
	uci -q set dns_rewrite.globals=dns_rewrite
	uci -q set dns_rewrite.globals.description='Local DNS rewrite list'
	uci -q commit dns_rewrite
}

if [ -n "$(uci -q get dhcp.@dnsmasq[0])" ]; then
	uci -q set dhcp.@dnsmasq[0].confdir='/etc/dnsmasq.d'
	mkdir -p /etc/dnsmasq.d
	uci -q commit dhcp
fi

[ -x /etc/init.d/dns-rewrite ] && /etc/init.d/dns-rewrite enable 2>/dev/null || true

exit 0
