[server]
use-ipv4=yes
use-ipv6=yes
allow-interfaces=br-lan,br-lan2
deny-interfaces=br-iot,br-guest,10g-2,tailscale0
check-response-ttl=no
use-iff-running=yes
disallow-other-stacks=no
cache-entries-max=512

[publish]
disable-publishing=yes
publish-addresses=no
publish-hinfo=no
publish-workstation=no
publish-domain=no

[reflector]
enable-reflector=yes
reflect-ipv=no

[rlimits]
rlimit-core=0
rlimit-data=8388608
rlimit-fsize=0
rlimit-nofile=256
rlimit-stack=4194304
rlimit-nproc=3
