#!/bin/sh
# One-shot after this image: pin NSS-friendly performance knobs.
# Separate filename so keep-settings upgrades re-apply (99-qol_nss_tailscale
# already ran on existing devices).

[ -n "$(uci -q get firewall.@defaults[0])" ] && {
	uci -q set firewall.@defaults[0].flow_offloading=0
	uci -q set firewall.@defaults[0].flow_offloading_hw=0
	uci -q commit firewall
}

if [ -n "$(uci -q get network.globals)" ]; then
	uci -q set network.globals.packet_steering='0'
	uci -q delete network.globals.steering_flows 2>/dev/null || true
	uci -q commit network
fi

[ -n "$(uci -q get ecm.@general[0])" ] && {
	uci -q set ecm.@general[0].enable_bridge_filtering=0
	uci -q commit ecm
}

[ -n "$(uci -q get pbuf.opt)" ] && {
	uci -q set pbuf.opt.memory_profile=auto
	uci -q set pbuf.opt.scaling_governor=performance
	uci -q set pbuf.opt.auto_scale=off
	uci -q commit pbuf
}

if [ -f /etc/config/skb_recycler ] || [ -n "$(uci -q get skb_recycler.opt)" ]; then
	uci -q set skb_recycler.opt=skb_recycler
	uci -q set skb_recycler.opt.enable='1'
	[ -z "$(uci -q get skb_recycler.opt.max_skbs)" ] && uci -q set skb_recycler.opt.max_skbs='1024'
	[ -z "$(uci -q get skb_recycler.opt.max_spare_skbs)" ] && uci -q set skb_recycler.opt.max_spare_skbs='256'
	uci -q commit skb_recycler
fi

exit 0
