#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=61

USE_PROCD=1
PROG=avahi-daemon

start_service() {
	mkdir -p /var/run/avahi
	chown avahi:avahi /var/run/avahi 2>/dev/null || true
	procd_open_instance
	procd_set_param command "$PROG"
	procd_append_param command -s
	procd_set_param file /etc/avahi/avahi-daemon.conf
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	procd_send_signal "$PROG"
}
